name: DEV - Pull Salesforce Metadata and Commit

on:
  schedule:
    - cron: "0 0 1 * SUN" # At 00:00 on Sunday
  workflow_dispatch: # Allows manual trigger

jobs:
  call-sync-from-sf:
    if: ${{ github.event_name == 'workflow_dispatch' || vars.DISABLE_SCHEDULE != 'TRUE' }}
    permissions: 
      contents: write
      pull-requests: write
    uses: ./.github/workflows/sync_from_sf.yml
    with:
      branch: dev
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      sfdx_auth_url: ${{ secrets.SFDX_DEV_AUTH_URL }}