name: Reusable Action - Pull Metadata from Salesforce and Commit

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      sfdx_auth_url:
        required: true

jobs:
  pull-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Gives write permission to the entire job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Set up Node.js (includes npm)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Salesforce CLI
      run: |
        npm install --global sfdx-cli
        sfdx --version

    - name: Authenticate Salesforce Org
      env:
        SFDX_AUTH_URL: ${{ secrets.sfdx_auth_url }}
      run: |
        echo $SFDX_AUTH_URL > sfdx.url
        sfdx auth:sfdxurl:store -f sfdx.url -a production
        rm sfdx.url

    - name: Pull Metadata
      run: |
        mkdir -p metadata
        sfdx force:source:retrieve -m ApexClass,ApexTrigger,CustomObject,ApexPage,AuraDefinitionBundle,LightningComponentBundle,FlowDefinition,Flow,EmailTemplate -u production -r ./metadata
        cp -r ./metadata/* ./force-app/main/default/
        rm -rf ./metadata

    - name: Configure Git
      run: |
        git config --global user.name "developerharb"
        git config --global user.email "developer@harborcoatconsulting.com"

    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ inputs.branch }}
      run: |
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        if [ "$(git status --porcelain)" != "" ]; then
          git add .
          git commit -m "Updated Salesforce Metadata: $(date)"
          git push origin ${BRANCH_NAME}
        else
          echo "No changes detected"
        fi
